version: "2"
services:
  node:
    image: "node:8.10.0-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    ports:
      - "8000:8081"

# Change version of node image as required
# Expose ports which you want according to node server
# Put the code inside app folder
# Make sure you have npm start in your package.json
# Map to host port as here it is matched to 8000
